<script>
	var backgound = '<div style="position: fixed; top: 0px; left: 0px; z-index: 99;  height: 100%;width: 100%; opacity: 0.5; background-color: rgb(85, 136, 153);"></div>';
</script>
<div id="auction_game" style="display:none">
<div class="left-col"></div>
<div class="right-col"></div>
</div>
<style>
#auction_game{
	width:100%;
	height:100%;
	max-height:800px;
}
.left-col,right-col{
	float:left;
}
.left-col{
	width:80%;
}
.right-col{
	width:20%;
}
</style>